baseURL: http://example.org/                  # Hosting location.
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
theme: Eclectic                               # Name of the theme
enableEmoji: true                             # Enable Emoticons
enableGitInfo: true                           # Allow access to Git data
