module:
  hugoVersion:
    min: 0.78.2
  imports:
    - path: github.com/hugoinaction/Resources
      mounts:
        - source: assets
          target: assets
    - path: github.com/hugoinaction/hugo-debug-utils
    - path: github.com/hugoinaction/AcmeShared
